Simple
TrinityCTAT/ctat-mutations pull request #20
Opened 2019-06-21 02:09 UTC by vrushali-broad

2019-06-21 14:20 UTC, brianjohnhaas requested changes
once these comments are addressed, I'll continue to review the rest and test execution.

thanks!

2019-06-21 14:20 UTC, brianjohnhaas commented on ctat_mutations
> -  / ____|__   __|/\|__   __|          |  \/  | |  | |__   __|/\|__   __|_   _/ __ \| \ | |
Is the fancy logo missing from your version?

2019-06-21 14:20 UTC, brianjohnhaas commented on ctat_mutations
> -import urllib.request # ctat-mutations requires this non-built-in python module.
I think we leave in the urllib.request here mostly as a way to ensure users have it installed, rather than having the software break when it reaches the cravat annotation step (which has that dependency, I think).

2019-06-21 14:20 UTC, brianjohnhaas commented on ctat_mutations
> -VERSION = "__BLEEDING_EDGE__"
let's keep a version tag.   It stays as '__BLEEDING_EDGE__' in the devel code, and we change it to an actual release value at the time of the release, which goes into the master branch.

2019-06-21 14:20 UTC, brianjohnhaas commented on ctat_mutations
> +VIZDIR = os.path.sep.join([os.path.dirname(os.path.realpath(__file__)), "igv_reports"])
we shouldn't be using igv_reports as an included subdirectory or module.  It should be centrally installed via python 'pip'.

2019-06-21 14:20 UTC, brianjohnhaas commented on ctat_mutations
> +            common_exac = os.path.join(test_lib, "small_exac_common_3_b37.vcf.gz")
when I had looked into mutect2 (gatk4), I thought it was using a 'gnomad' file rather than 'exac'.  Is the 'gnomad' one  newer/better?

2019-06-21 14:20 UTC, brianjohnhaas commented on ctat_mutations
> -                                           "FilterMutectCalls",
Is this correct?  FilterMutectCalls followed by SelectVariants in the same gatk call/command?

2019-06-21 14:20 UTC, brianjohnhaas commented on ctat_mutations
> -                                           "FilterMutectCalls",
I think FilterMutectCalls is not supposed to be there.  This CNN thing looks related to haplotypecaller and not mutect

2019-06-21 14:20 UTC, brianjohnhaas commented on ctat_mutations
> +                                 str_unique_id,
should we remove the samtools based var calling?  If we want to do it, we could make a separate script rather than using this one.

2019-06-21 14:20 UTC, brianjohnhaas commented on ctat_mutations
> +            common_exac = os.path.join(test_lib, "small_exac_common_3_b37.vcf.gz")
The gnomad resources appear to be here:
http://bioinfo5pilm46.mit.edu/software/GATK/resources/

2019-06-21 16:51 UTC, vrushali-broad commented on ctat_mutations
> -  / ____|__   __|/\|__   __|          |  \/  | |  | |__   __|/\|__   __|_   _/ __ \| \ | |
Fixed it!

2019-06-21 16:51 UTC, vrushali-broad commented on ctat_mutations
> -import urllib.request # ctat-mutations requires this non-built-in python module.
fixed it!

2019-06-21 16:51 UTC, vrushali-broad commented on ctat_mutations
> -VERSION = "__BLEEDING_EDGE__"
Fixed!

2019-06-21 17:47 UTC, vrushali-broad commented on ctat_mutations
> +VIZDIR = os.path.sep.join([os.path.dirname(os.path.realpath(__file__)), "igv_reports"])
Done!

2019-06-21 18:00 UTC, vrushali-broad commented on ctat_mutations
> +                                 str_unique_id,
Removed the function.

2019-06-21 19:03 UTC, vrushali-broad commented on ctat_mutations
> +            common_exac = os.path.join(test_lib, "small_exac_common_3_b37.vcf.gz")
Resolved

2019-06-21 19:04 UTC, vrushali-broad commented on ctat_mutations
> -                                           "FilterMutectCalls",
Keep both FilterMutectCalls (only adds flags) and SelectVariants (removes SNPs with chosen flags)

2019-06-21 19:47 UTC, brianjohnhaas reviewed
thx Vrushali.  Please address the remaining comments, make sure that the refined code works w/ the integrated test suite, and then I'll take one last look before it goes in.

2019-06-21 19:47 UTC, brianjohnhaas commented on ctat_mutations
> -import urllib.request # ctat-mutations requires this non-built-in python module.
still shows the line as being deleted.  Did you restore it?

2019-06-21 19:47 UTC, brianjohnhaas commented on ctat_mutations
> +STR_FILTERING_MUTECT2_LROM = "MUTECT2_LROM"
can you add a comment indicating what LROM stands for?    I keep forgetting.

2019-06-21 19:47 UTC, brianjohnhaas commented on ctat_mutations
> -STR_CRAVAT_HEADER_INFO = os.path.join(BASEDIR, "meta/cravat_annotation.txt")
this cravat_annotation.txt file used to be included in the mutation lib, but I moved it to github here.  Are you removing it again?  Might need to restore this.  It made more sense to keep it in the repo than in the mutation lib given that it worked for both the hg19 and hg38 w/o modification, and it was small enough.

2019-06-21 19:47 UTC, brianjohnhaas commented on ctat_mutations
> +            # if genome_resource is provided
germline resource, not genome resource

2019-06-21 19:47 UTC, brianjohnhaas commented on ctat_mutations
> +                                     "--germline-resource", gnomad,
these are two very different mutect2 calls.  Do we have good justification for keeping them both, and for why one must be very different from the other?  (if so, let's include a comment/link to the gatk url indicating the settings).

2019-06-21 19:47 UTC, brianjohnhaas commented on ctat_mutations
> +    def func_do_filtering_bcftools(self, args_call, str_variants_file):
thought you were removing this

2019-06-21 19:47 UTC, brianjohnhaas commented on ctat_mutations
> +                variant_calling_cmd, str_variant_file = self.Variant_Calling_SAMTOOLS(args_call = args_parsed,
do we need the samtools based variant calling code here?

2019-06-28 13:37 UTC, brianjohnhaas commented
I'm merging in now and will work on some further refinements.

2019-06-28 13:37 UTC, merged